# Generated by Django 5.1 on 2024-08-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='age',
            field=models.IntegerField(),
        ),
    ]
